# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  frontend:
    ports:
      - 5002:80
      - 5001:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ApiConfigs__ConcertCatalog__Uri=http://catalog
      - ApiConfigs__Ordering__Uri=http://ordering
    #volumes:
      #- ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      #- ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      #- ~/.vsdbg:/remote_debugger:rw

  catalog:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5003:80"

  ordering:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5004:80"