apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secretstore
  namespace: default
spec:
  type: secretstores.local.env
  version: v1
  metadata:
  - name: secretsFile
    value: ./components/secret2s.json
  - name: nestedSeparator
    value: ":"